import Providers from "./providers/Providers"
import RTProvider from "./providers/RTProvider"

export const metadata = {
  title: 'MegaTexnika',
  description: 'Generated by Next.js',
}

export default function Rootlayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <RTProvider>
     <Providers>
     <body>{children}</body>
     </Providers>
     </RTProvider>
    </html>
  )
}
