import Providers from "./providers/Providers"

export const metadata = {
  title: 'MegaTexnika',
  description: 'Generated by Next.js',
}

export default function Rootlayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
     <Providers>
     <body>{children}</body>
     </Providers>
    </html>
  )
}
