import "../style.css"
import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import { Box, ThemeProvider } from "@mui/material";
import Header from "../(components)/header/Header";
import Footer from "../(components)/footer/Footer";
import theme from "@/theme/theme";
const inter = Inter({ subsets: ["latin"] });

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MagaTexnika",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
        <Header/>
        <Box sx={{backgroundColor:""}}>
         
            {children}
         
        </Box>
        <Footer/>
        </>
  );
}
