import "../style.css"
import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import {Box, ThemeProvider } from "@mui/material";
import Header from "../(components)/header/Header";
import Footer from "../(components)/footer/Footer";
import theme from "@/theme/theme";
import SideMenu from "./components/SideMenu";
import UserInfo from "./components/UserInfo";
import Sidebar from "./components/Sidebar";
import AdminMobileMenu from "./components/AdninMobileMenu";
const inter = Inter({ subsets: ["latin"] });

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MagaTexnika",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Box>
      <Box sx={{display:{xs:"block",md:"none"}}}>
           <AdminMobileMenu/>
        </Box>
        <Box sx={{display:"flex",gap:2,height:"100%"}}>
        
        <Box sx={{flex:{md:2,xs:0},display:{xs:"none",lg:"block"}}}>
            <Sidebar/>
        </Box>
        <Box sx={{flex:{md:10,xs:12}}}>
            {children}
        </Box>
        </Box>
    </Box>
    
  );
}
