import "../style.css"
import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import {Box, ThemeProvider } from "@mui/material";
import Header from "../(components)/header/Header";
import Footer from "../(components)/footer/Footer";
import theme from "@/theme/theme";
import SideMenu from "./components/SideMenu";
import UserInfo from "./components/UserInfo";
import Sidebar from "./components/Sidebar";
const inter = Inter({ subsets: ["latin"] });

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MagaTexnika",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Box sx={{display:"flex",gap:2,height:"100%"}}>
        <Box sx={{flex:2}}>
            <Sidebar/>
        </Box>
        <Box sx={{flex:10}}>
            {children}
        </Box>
        </Box>
  );
}
